routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/cache', function () {
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    return "<h1>Cache Clear</h1>";
});

Route::get('/home-repairing-services', 'HomeServiceController@index')->name('home-services.index')->middleware('auth');
Route::post('/home-services/home-repairing-services', 'HomeServiceController@HomeRepairingServices')->middleware('auth');
Route::post('/home-services/validate-step-one', 'HomeServiceController@validateStepOne')->middleware('auth');
Route::post('/home-services/validate-step-two', 'HomeServiceController@validateStepTwo')->middleware('auth');
Route::post('/home-services/validate-step-three', 'HomeServiceController@validateStepThree')->middleware('auth');
Route::post('/home-services/validate-step-four', 'HomeServiceController@validateStepFour')->middleware('auth');
Route::post('/home-services/validate-step-five', 'HomeServiceController@validateStepFive')->middleware('auth');
Route::get('sendSMS', 'TwilioSMSController@index')->name('sms');

Route::get('/oils', 'EngineOilController@index')->name('engine-oil.index');
Route::post('/add-to-cart/oil/{id}', 'EngineOilController@addOil')->middleware('auth');
Route::get('/get-cart/', 'CartController@getCart');

// Route::post('/engine-oil/engine-oil-purchase', 'EngineOilController@engineOilPurchase')->middleware('auth');
// Route::post('/engine-oil/validate-step-one', 'EngineOilController@validateStepOne')->middleware('auth');

Route::post('/workshop/reviews', 'PageController@reviewsSubmit')->middleware('auth');
Route::post('/workshop/reviews/{workshop}', 'PageController@reviewsShow');

Route::post('/add-to-cart/spare-part/{id}', 'CartController@addSparePart')->middleware('auth');
Route::post('/change-up-cart/price/{cart}', 'CartController@changeUpCartPrice')->middleware('auth');
Route::post('/change-down-cart/price/{cart}', 'CartController@changeDownCartPrice')->middleware('auth');
Route::post('/remove/cart/{cart}', 'CartController@removeCart')->middleware('auth');
Route::get('/cart', 'CartController@index')->name('pages.cart')->middleware('auth');
Route::get('/cart/checkout', 'CartController@cartCheckout')->name('pages.cart-checkout')->middleware('auth');
Route::post('/cart/checkout/place-order', 'CartController@placeOrder')->name('pages.place-order')->middleware('auth');

Route::get('/', 'PageController@index')->name('pages.home');
Route::get('/about', 'PageController@about')->name('pages.about');
Route::get('/customer-complaints', 'PageController@customerComplaints')->name('pages.customer-complaints');
Route::post('/customer-complaints/submit', 'PageController@complaintsSubmit')->name('pages.complaints.submit');
Route::get('/emergency-towing-repairing', 'PageController@emergencyTowing')->name('pages.emergency-towing')->middleware('auth');
Route::post('/emergency-towing-repairing/request', 'PageController@emergencyTowingRequest')->name('pages.emergency-towing.request')->middleware('auth');

Route::get('/workshops', 'PageController@workshops')->name('pages.frontend.workshops');
Route::get('/workshop/{slug}/details', 'PageController@workshopDetails')->name('pages.frontend.workshop-details');
Route::post('/search/workshops', 'PageController@searchWorkshops')->name('pages.search.workshops');
Route::get('/spare-parts', 'PageController@spareParts')->name('pages.frontend.spare-parts');
Route::get('/spare-parts/{slug}/details', 'PageController@sparePartDetails')->name('pages.frontend.spare-part-details');
//Route::get('/oils', 'PageController@oils')->name('pages.frontend.oils');
Route::get('/oils/{slug}/details', 'PageController@oilDetails')->name('pages.frontend.oil-details');
Route::get('/services', 'PageController@services')->name('pages.frontend.services');
Route::get('/service/{slug}/details', 'PageController@serviceDetails')->name('pages.frontend.service-details');

Route::post('/search/spare-parts', 'PageController@searchSpareParts')->name('pages.search.spare-parts');
Route::get('/contact-us', 'PageController@contactUs')->name('pages.contact-us');
Route::get('/service-repairs-maintenance', 'PageController@serviceRepairsMaintenance')->name('pages.maintenance');
Route::post('/vehicle-information', 'PageController@vehicleInformation');
Route::post('/validate-step-one', 'PageController@validateStepOne');
Route::post('/validate-step-two', 'PageController@validateStepTwo');
Route::post('/validate-step-three', 'PageController@validateStepThree');
Route::post('/validate-step-four', 'PageController@validateStepFour');
Route::post('/validate-step-five', 'PageController@validateStepFive');
Route::Post('/get-all/models/{id}', 'PageController@getAll');
Route::Post('/get-all/spare-parts/{id}', 'PageController@getAllParts');
Route::Post('/get-all/workshop/spare-parts', 'PageController@getAllWorkshopParts');
Route::Post('/get/workshop/{workshop}/car/{car}/model/{id}', 'PageController@getWorkshopCarModel');
Route::Post('/get-all/workshop/model/spare-parts/{id}', 'PageController@getAllModelParts');
Route::Post('/get-all/workshop/model/spare-parts', 'PageController@getAllWorkshopParts');
Route::Post('/get-all/price/spare-parts', 'PageController@getAllPriceParts');
Route::Post('/get-all/workshop/models/{model}/cars/{car}/spare-parts', 'PageController@getAllWorkshopModelCarParts');

Route::Post('/get-all/workshop/{city}', 'PageController@getAllWorkshopCities');
Route::Post('/get-all/workshop', 'PageController@getAllWorkshop');
Route::Post('/get-all/services/{workshop}', 'PageController@getAllServices');
Route::Post('/get-all/car/models/{id}', 'PageController@getAllCarModels');

Auth::routes();
Route::post('workshop/register', 'Auth\RegisterController@workshopRegister')->name('workshop.register');

Route::group(['prefix' => 'admin', "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/', function () {
        return redirect(route("admin.login"));
    });
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['prefix' => 'admin', "middleware" => "auth:admin", "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/change-password', 'ChangePasswordController@changePassword')->name('change-password.edit');
    Route::put('/change-password', 'ChangePasswordController@updatePassword')->name('change-password.update');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin', "namespace" => "Admin"], function () {
    Route::get('/', 'PageController@index')->name('admin.pages.home');
    Route::post('/filter', 'PageController@filter')->name('admin.home.filter');

    Route::get('/complaints', 'PageController@complaints')->name('complaints');
    Route::get('/emergencies-towing', 'EmergencyController@index')->name('emergencies-towing.index');

    Route::resource('workshops', 'WorkshopController');
    Route::get('/workshop/change-password', 'WorkshopController@changePassword')->name('admin.workshops.change-password');
    Route::put('/workshop/update-password', 'WorkshopController@updatePassword')->name('admin.workshops.update-password');
    Route::get('/workshop/{id}/set-status/{status}', 'WorkshopController@setStatus')->name('admin.workshop-status');

    Route::resource('reviews', 'ReviewController');
    Route::resource('oils', 'OilController');
    Route::get('/oil/image-delete/{oil}/{image}', 'OilController@delete')->name('oil.picture.delete');

    Route::get('/service/image-delete/{service}/{image}', 'ServiceController@delete')->name('service.picture.delete');

    Route::resource('services', 'ServiceController');
    Route::resource('bookings', 'BookingController');
    Route::resource('orders', 'OrderController');
    Route::resource('cars', 'CarController');
    Route::resource('models', 'ModelController');
    Route::resource('oils-dealers', 'OilsDealerController');
    Route::resource('parts-dealers', 'PartsDealerController');
    Route::resource('labours', 'LabourController');

    Route::post('/order/status', "OrderController@status")->name("order.status");
    Route::post('/booking/status', "BookingController@status")->name("booking.status");

    Route::resource('parts', 'SparePartsController');
    Route::get('/part/image-delete/{part}/{image}', 'SparePartsController@delete')->name('part.picture.delete');

    Route::resource('users', 'UserController');
    Route::get('/{id}/set-status/{status}', 'UserController@setStatus')->name('admin.user-status');
    Route::get('/user/{user}/change-password', 'UserController@changePassword')->name('admin.users.change-password');
    Route::put('/user/{user}/update-password', 'UserController@updatePassword')->name('admin.users.update-password');
    // Contact Inquiries
    Route::get('/general-settings/create', "GeneralSettingController@create")->name("general-settings.create");
    Route::post('/general-settings', "GeneralSettingController@store")->name("general-settings.store");

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $guarded = [];

    public function workshop()
    {
        return $this->belongsToMany(Workshop::class, 'service_workshops');
    }

    public function pictures()
    {
        return $this->hasMany(ServicesPictures::class);
    }

    public function prices()
    {
        return $this->hasMany(ServicesLabours::class);
    }
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Labour;
use App\Service;
use App\ServicesLabours;
use App\ServicesPictures;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $services = Service::latest()->paginate(10);
        return view('admin.services.index')->with(compact(['services']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $labours = Labour::all();
        return view('admin.services.create', compact('labours'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'price' => ['required'],
            'image' => ['required', 'array'],
        ]);

        $slug = Str::slug($data['name'], '-');
        $service = new Service;
        $service->name = $request->name;
        $service->slug = $slug;
        $service->description = $request->description;
        $service->discount = $request->discount;
        $service->save();
        $id = $service->id;
        $prices = $request->price;
        $labours = $request->labour;
        foreach ($prices as $index => $price) {
            ServicesLabours::create(['service_id' => $id, 'labour_id' => $labours[$index], 'price' => $price]);

        }
        $images = $request->image;

        foreach ($images as $image) {
            $filename = Str::random(15) . '.' . $image->extension();
            Storage::putFileAs("public", $image, $filename);
            ServicesPictures::create(['service_id' => $id, 'path' => $filename]);
        }

        return redirect()->route('services.index')->with('success', 'Service created successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Service $service)
    {
        $pictures = ServicesPictures::where('service_id', $service->id)->get();
        $prices = ServicesLabours::where('service_id', $service->id)->get();
        $labours = Labour::all();

        return view('admin.services.edit')->with(compact(['service', 'pictures', 'prices', 'labours']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Service $service)
    {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'price' => ['required'],

        ]);

        $slug = Str::slug($data['name'], '-');
        $service = Service::find($service->id);
        $service->name = $request->name;
        $service->slug = $slug;
        $service->description = $request->description;
        $service->discount = $request->discount;
        $service->save();
        $id = $service->id;
        $prices = $request->price;
        $labours = $request->labour;
        foreach ($prices as $index => $price) {
            ServicesLabours::where(['service_id' => $id, 'labour_id' => $labours[$index]])->update(['price' => $price]);

        }
        $images = $request->image;
        if ($images) {
            foreach ($images as $image) {
                $filename = Str::random(15) . '.' . $image->extension();
                Storage::putFileAs("public", $image, $filename);
                ServicesPictures::create(['service_id' => $id, 'path' => $filename]);
            }
        }
        return redirect()->route('services.index')->with('success', 'Service updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {

        Storage::delete('public/' . $service->image);
        $service->delete();
        return redirect()->back();
    }

    public function delete(Request $request, $id, $image)
    {
        Storage::delete('public/' . $image);
        ServicesPictures::where(['service_id' => $id, 'path' => $image])->delete();

        $request->session()->flash('message', 'Delete Image successfully');
        $request->session()->flash('alert-class', 'alert alert-success');
        return redirect()->back();
    }

    public function show(Service $service)
    {
        $pictures = ServicesPictures::where('service_id', $service->id)->get();
        $prices = ServicesLabours::where('service_id', $service->id)->get();
        $labours = Labour::all();

        return view('admin.services.show')->with(compact(['service', 'pictures', 'prices', 'labours']));
    }

}

app/Http/Controllers/Admin/WorkshopController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Workshop;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use App\Mail\WorkshopRegisterMail;
class WorkshopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $workshops = Workshop::orderBy('status', 'ASC')->latest()->paginate(10);
        return view('admin.workshops.index')->with(compact(['workshops']));
    }

    public function changePassword()
    {
        return view('admin.workshops.change-password');
    }

    public function updatePassword(Request $request)
    {
        $data = $request->validate([
            'new_password' => ['required', 'string', 'min:8'],
            'confirm_password' => ['required_with:new_password', ' same:new_password', 'string', 'min:8'],
        ]);
        $workshop = Workshop::where('id', Auth::user()->id)->first();
        $workshop->update([
            'password' => Hash::make($data['new_password'])
        ]);
        $request->session()->flash('message', 'Password updated successfully');
        $request->session()->flash('alert-class', 'alert alert-success');
        return redirect()->route('workshop.index');
    }

    public function setStatus($id, $status)
    {
        $workshop = Workshop::where('id', $id)->first();
        $workshop->status = $status;
        $workshop->save();
        if($workshop->status == 1){
            $status = "Approved";
            Mail::to($workshop->email)->send(new WorkshopRegisterMail());
        }
        return response()->json($workshop);
    }
}

app/Http/Controllers/Workshop/EmergencyController.php
<?php

namespace App\Http\Controllers\Workshop;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class EmergencyController extends Controller
{
    //
}

resources/views/workshop/services/create.blade.php
@extends('workshop.layouts.layout')

@section('heading')
    <h4>
        <a href="{{ route('workshop.index') }}">
            <i class="icon-arrow-left52 mr-2"></i>
        </a>
        <span class="font-weight-semibold">Home - Services</span>
    </h4>
@endsection

@section('breadcrumbs')
    <div class="breadcrumb">
        <a href="{{ route('services.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item">Service</span>
        <span class="breadcrumb-item active">Create</span>
    </div>
@endsection

@section('content')
    @include('admin.partials.header')
    <div class="content">
        @include('common.partials.flash')

        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Services</h5>
            </div>

            <div class="card-body">
                <form action="{{ route('services.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label class="font-weight-semibold @error('name') text-danger @enderror">Name <span
                                class="text-red">*</span></label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="text" name="name" value="{{ old('name') }}"
                                class="form-control @error('name') border-danger @enderror" required>
                            @error('name')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('name')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold @error('price') text-danger @enderror">Price <span
                                class="text-red">*</span></label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="number" name="price" value="{{ old('price') }}"
                                class="form-control @error('price') border-danger @enderror" required>
                            @error('price')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('price')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <input type="hidden" name="workshop_id" value="{{ auth()->user()->id }}"/>
                    <div class="form-group">
                        <label class="font-weight-semibold @error('image') text-danger @enderror">Image
                            <span class="text-red">*</span></label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="file" accept=".jpeg,.png,.bmp,.gif,.svg,.webp,.jpg" name="image">
                            <span class="form-text text-muted">Accepted formats: jpeg, png, bmp, gif, svg, jpg, or webp</span>
                            @error('image')
                            <div class="form-control-feedback text-danger">
                                <i class="feature_image-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('image')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit <i class="icon-paperplane ml-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/workshop/services/edit.blade.php
@extends('workshop.layouts.layout')

@section('heading')
    <h4>
        <a href="{{ route('workshop.index') }}">
            <i class="icon-arrow-left52 mr-2"></i>
        </a>
        <span class="font-weight-semibold">Home - Service</span>
    </h4>
@endsection

@section('breadcrumbs')
    <div class="breadcrumb">
        <a href="{{ route('services.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item">Service: {{ $service->name }}</span>
        <span class="breadcrumb-item active">Edit</span>
    </div>
@endsection
@section('content')
    @include('admin.partials.header')
    <div class="content">
        @include('common.partials.flash')
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Service</h5>
            </div>
            <div class="card-body">
                <form action="{{ route('services.update', $service->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label class="font-weight-semibold @error('name') text-danger @enderror">Name <span
                                class="text-red">*</span></label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="text" name="name" value="{{ $service->name }}"
                                class="form-control @error('name') border-danger @enderror" required>
                            @error('name')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('name')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold @error('price') text-danger @enderror">Price <span
                                class="text-red">*</span></label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="number" name="price" value="{{ $service->price }}"
                                class="form-control @error('price') border-danger @enderror" required>
                            @error('price')
                            <div class="form-control-feedback text-danger">
                                <i class="icon-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('price')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <input type="hidden" name="workshop_id" value="{{ auth()->user()->id }}"/>
                    <div class="form-group">
                        <label style="display: block;"
                            class="font-weight-semibold @error('image') text-danger @enderror">Image <span
                                class="text-red">*</span></label>
                        <div class="d-inline-block" style="position: relative;margin-bottom: inherit;">
                        @if($service->image)
                                <div class="d-inline-block" style="position:relative;margin-bottom: inherit; ">
                                    <img src="{{ asset('/storage/'. $service->image) }}" height="200px" width="200px"/>
                                </div>
                        @else
                            <p>No Image Found</p>
                        @endif
                        <input type="file" accept=".jpeg,.png,.bmp,.gif,.svg,.webp,.jpg" name="image">
                        <span class="form-text text-muted">Accepted formats: jpeg, png, bmp, gif, svg, jpg, or webp</span>
                        @error('image')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                        </div>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit <i class="icon-paperplane ml-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/workshop/services/index.blade.php
@extends('workshop.layouts.layout')

@section('heading')
    <h4><a href="{{ route('services.index') }}"><i class="icon-arrow-left52 mr-2"></i></a> <span
            class="font-weight-semibold">Home - Services</span> - View All</h4>
@endsection

@section('breadcrumbs')
    <div class="breadcrumb">
        <a href="{{ route('services.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item">Services</span>
        <span class="breadcrumb-item active">View All</span>
    </div>
@endsection

@section('content')
   @include('admin.partials.header')
    <div class="content">
        @include('common.partials.flash')
        <div class="card has-table">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">All Services</h5>
                <div class="header-elements">
                    <a href="{{ route('services.create') }}" class="mt-2 btn btn-primary">
                        Create New Service
                    </a>
                </div>
            </div>
            <table class="table datatable-basic">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Created At</th>
                    <th>Modified At</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                @forelse ($services as $service)
                    <tr>
                        <td>
                            <img style="width:150px;" alt="{{ $service->name }}" src={{ asset('/storage/' . $service->image)}} />
                        </td>
                        <td>{{ $service->name }}</td>
                        <td>{{ $service->price }}</td>
                        <td>{{ $service->created_at }}</td>
                        <td>{{ $service->updated_at }}</td>
                        <td class="text-center">
                            <div class="list-icons">
                                <div class="dropdown">
                                    <a href="#" class="list-icons-item" data-toggle="dropdown">
                                        <i class="icon-menu9"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a href="{{ route('services.edit', $service->id) }}"
                                           class="dropdown-item"><i class="icon-pencil5"></i> Edit
                                        </a>
                                        <a href="#" class="dropdown-item"
                                           onclick="event.preventDefault(); if(confirm('Are you sure you want to perform this action?')){document.getElementById('delete-service-{{ $service->id }}-form').submit();}">
                                            <i class="icon-trash"></i>
                                            Delete
                                        </a>
                                        <form action="{{ route('services.destroy', $service->id) }}"
                                              id="delete-service-{{ $service->id }}-form" method="POST"
                                              style="display: none;">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7">
                            <div class="alert alert-info text-center">
                                No Services Added So Far
                                <br>
                                <a href="{{ route('services.create') }}" class="mt-2 btn btn-primary">
                                    Create New Service
                                </a>
                            </div>
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            {!! $services->links() !!}
        </div>
    </div>
@endsection