routes/web.php
Route::get('/spare-parts', 'PageController@spareParts')->name('pages.frontend.spare-parts');
Route::get('/spare-parts/{slug}/details', 'PageController@sparePartDetails')->name('pages.frontend.spare-part-details');
//Route::get('/oils', 'PageController@oils')->name('pages.frontend.oils');
Route::get('/oils/{slug}/details', 'PageController@oilDetails')->name('pages.frontend.oil-details');
Route::get('/services', 'PageController@services')->name('pages.frontend.services');
Route::get('/service/{slug}/details', 'PageController@serviceDetails')->name('pages.frontend.service-details');

Route::post('/search/spare-parts', 'PageController@searchSpareParts')->name('pages.search.spare-parts');
Route::get('/contact-us', 'PageController@contactUs')->name('pages.contact-us');
Route::get('/service-repairs-maintenance', 'PageController@serviceRepairsMaintenance')->name('pages.maintenance');
Route::post('/vehicle-information', 'PageController@vehicleInformation');
Route::post('/validate-step-one', 'PageController@validateStepOne');
Route::post('/validate-step-two', 'PageController@validateStepTwo');
Route::post('/validate-step-three', 'PageController@validateStepThree');
Route::post('/validate-step-four', 'PageController@validateStepFour');
Route::post('/validate-step-five', 'PageController@validateStepFive');
Route::Post('/get-all/models/{id}', 'PageController@getAll');
Route::Post('/get-all/spare-parts/{id}', 'PageController@getAllParts');
Route::Post('/get-all/workshop/spare-parts', 'PageController@getAllWorkshopParts');
Route::Post('/get/workshop/{workshop}/car/{car}/model/{id}', 'PageController@getWorkshopCarModel');
Route::Post('/get-all/workshop/model/spare-parts/{id}', 'PageController@getAllModelParts');
Route::Post('/get-all/workshop/model/spare-parts', 'PageController@getAllWorkshopParts');
Route::Post('/get-all/price/spare-parts', 'PageController@getAllPriceParts');
Route::Post('/get-all/workshop/models/{model}/cars/{car}/spare-parts', 'PageController@getAllWorkshopModelCarParts');

Route::Post('/get-all/workshop/{city}', 'PageController@getAllWorkshopCities');
Route::Post('/get-all/workshop', 'PageController@getAllWorkshop');
Route::Post('/get-all/services/{workshop}', 'PageController@getAllServices');
Route::Post('/get-all/car/models/{id}', 'PageController@getAllCarModels');

Auth::routes();
Route::post('workshop/register', 'Auth\RegisterController@workshopRegister')->name('workshop.register');

Route::group(['prefix' => 'admin', "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/', function () {
        return redirect(route("admin.login"));
    });
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['prefix' => 'admin', "middleware" => "auth:admin", "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/change-password', 'ChangePasswordController@changePassword')->name('change-password.edit');
    Route::put('/change-password', 'ChangePasswordController@updatePassword')->name('change-password.update');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin', "namespace" => "Admin"], function () {
    Route::get('/', 'PageController@index')->name('admin.pages.home');
    Route::post('/filter', 'PageController@filter')->name('admin.home.filter');

    Route::get('/complaints', 'PageController@complaints')->name('complaints');
    Route::get('/emergencies-towing', 'EmergencyController@index')->name('emergencies-towing.index');

    Route::resource('workshops', 'WorkshopController');
    Route::get('/workshop/change-password', 'WorkshopController@changePassword')->name('admin.workshops.change-password');
    Route::put('/workshop/update-password', 'WorkshopController@updatePassword')->name('admin.workshops.update-password');
    Route::get('/workshop/{id}/set-status/{status}', 'WorkshopController@setStatus')->name('admin.workshop-status');

    Route::resource('reviews', 'ReviewController');
    Route::resource('oils', 'OilController');
    Route::get('/oil/image-delete/{oil}/{image}', 'OilController@delete')->name('oil.picture.delete');

    Route::get('/service/image-delete/{service}/{image}', 'ServiceController@delete')->name('service.picture.delete');

    Route::resource('services', 'ServiceController');
    Route::resource('bookings', 'BookingController');
    Route::resource('orders', 'OrderController');
    Route::resource('cars', 'CarController');
    Route::resource('models', 'ModelController');
    Route::resource('oils-dealers', 'OilsDealerController');
    Route::resource('parts-dealers', 'PartsDealerController');
    Route::resource('labours', 'LabourController');

    Route::post('/order/status', "OrderController@status")->name("order.status");
    Route::post('/booking/status', "BookingController@status")->name("booking.status");

    Route::resource('parts', 'SparePartsController');
    Route::get('/part/image-delete/{part}/{image}', 'SparePartsController@delete')->name('part.picture.delete');

    Route::resource('users', 'UserController');
    Route::get('/{id}/set-status/{status}', 'UserController@setStatus')->name('admin.user-status');
    Route::get('/user/{user}/change-password', 'UserController@changePassword')->name('admin.users.change-password');
    Route::put('/user/{user}/update-password', 'UserController@updatePassword')->name('admin.users.update-password');
    // Contact Inquiries
    Route::get('/general-settings/create', "GeneralSettingController@create")->name("general-settings.create");
    Route::post('/general-settings', "GeneralSettingController@store")->name("general-settings.store");
    Route::get('/general-settings/edit', "GeneralSettingController@edit")->name("general-settings.edit");
    Route::put('/general-settings', "GeneralSettingController@update")->name("general-settings.update");
    Route::resource('contact-enquiries', 'ContactEnquiryController');

});

Route::group(['prefix' => 'workshop'], function () {
    Route::get('/', function () {
        return redirect(route("workshop.login"));
    });
    Route::get('login', 'WorkshopAuth\LoginController@showLoginForm')->name('workshop.login');
    Route::post('login', 'WorkshopAuth\LoginController@login')->name('workshop.login');
    Route::post('/password/email', 'WorkshopAuth\ForgotPasswordController@sendResetLinkEmail')->name('workshop.password.email');
    Route::get('/password/reset', 'WorkshopAuth\ForgotPasswordController@showLinkRequestForm')->name('workshop.password.request');
    Route::post('/password/reset', 'WorkshopAuth\ResetPasswordController@reset')->name('workshop.password.update');
    Route::get('password/reset/{token}', 'WorkshopAuth\ResetPasswordController@showResetForm')->name('workshop.password.reset');
});

Route::group(['prefix' => 'workshop', 'middleware' => 'auth:workshop-user'], function () {
    Route::get('/overview', 'Workshop\BackendController@index')->name('workshop.index');
    // Route::get('/complaint', 'Workshop\BackendController@complaints')->name('complaint');

    Route::resource('booking', 'Workshop\BookingController');
    Route::get('/booking/{booking}/set-status/{status}', 'Workshop\BookingController@setStatus');
    Route::get('/booking/{booking}/edit/profile', 'Workshop\BookingController@editProfile')->name('workshop.edit.profile');
    Route::post('/booking/{booking}/update/profile', 'Workshop\BookingController@updateProfile')->name('workshop.update.profile');

    Route::resource('order', 'Workshop\OrderController');
    Route::get('/order/{id}/set-status/{status}', 'Workshop\OrderController@setStatus');

    Route::resource('review', 'Workshop\ReviewController');
    Route::resource('posts', 'Workshop\PostController');
    Route::get('/posts/image-delete/{post}/{image}', 'Workshop\PostController@delete')->name('post.delete');
    Route::post('/get-all/models/{id}', 'Workshop\BackendController@getAll');
    // Route::get('/users', 'Workshop\BackendController@user')->name('workshop.users');

    Route::get('/profile/{workshop}', 'Workshop\BackendController@editProfile')->name('workshop.profile.edit');
    Route::put('/profile/{workshop}', 'Workshop\BackendController@updateProfile')->name('workshop.profile.update');

    Route::get('/change-password', 'Workshop\ChangePasswordController@changePassword')->name('workshop.change-password.edit');
    Route::put('/change-password', 'Workshop\ChangePasswordController@updatePassword')->name('workshop.change-password.update');
    Route::post('logout', 'WorkshopAuth\LoginController@logout')->name('workshop.logout');
});

Route::get('/create-symlink', function () {
    $projectFolder = base_path() . '/../';
    // The file that you want to create a symlink of
    $source = $projectFolder . "/FhJfSkEKkshfpr/storage/app/public";
    // The path where you want to create the symlink of the above
    $destination = $projectFolder . "/storage";

    if (file_exists($destination)) {
        if (is_link($destination)) {
            return "<h1>Symlink already exists</h1>";
        }
    } else {
        symlink($source, $destination);
        return "<h1>Symlink created successfully</h1>";
    }
});

Route::get('/remove-symlink', function () {
    $projectFolder = base_path() . '/../';
    $destination = $projectFolder . "/storage";
    if (file_exists($destination)) {
        if (is_link($destination)) {
            unlink($destination);
            return "<h1>Removed symlink</h1>";
        }

app/Http/Controllers/Admin/OilsDealerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Role;

class OilsDealerController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $dealers = Admin::role('oil_dealer')->paginate(10);

        return view('admin.oils-dealer.index', compact('dealers'));
    }

    public function create()
    {
        return view('admin.oils-dealer.create');
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'unique:admins'],
            'contact' => ['required'],
            'nic' => ['required', 'unique:admins'],
            'address' => ['required', 'string'],
            'city' => ['required', 'string'],

        ]);

        $dealer = new Admin;
        $dealer->username = $request->name;
        $dealer->business_name = $request->business_name;
        $dealer->contact = $request->contact;
        $dealer->email = $request->email;
        $dealer->nic = $request->nic;
        $dealer->address = $request->address;
        $dealer->city = $request->city;
        $password = '12345678';
        $dealer->password = Hash::make($password);

        $image = $request->image;
        if (isset($image)) {
            $filename = Str::random(15) . '.' . $image->extension();
            Storage::putFileAs("public", $image, $filename);
            $dealer->picture = $filename;
        } else {
            $dealer->picture = '';
        }

        $dealer->save();

        $role = Role::where('name', 'oil_dealer')->first();
        $user = Admin::where(['id' => $dealer->id])->first();
        $user->assignRole($role);

        return redirect()->route('oils-dealers.index')->with('success', 'Dealer created successfully.');
    }

    public function edit($id)
    {
        $dealer = Admin::find($id);
        return view('admin.oils-dealer.edit', compact('dealer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'contact' => ['required'],
            'nic' => ['required'],
            'address' => ['required', 'string'],
            'city' => ['required', 'string'],

        ]);

        $dealer = Admin::find($id);
        $dealer->username = $request->name;
        $dealer->business_name = $request->business_name;
        $dealer->contact = $request->contact;
        $dealer->email = $request->email;
        $dealer->nic = $request->nic;
        $dealer->address = $request->address;
        $dealer->city = $request->city;
        $dealer->password = Hash::make($request->password);
        if (isset($request->image)) {
            $image = $request->image;

            $filename = Str::random(15) . '.' . $image->extension();
            Storage::putFileAs("public", $image, $filename);
            $dealer->picture = $filename;

        }
        $dealer->save();

        return redirect()->route('oils-dealers.index')->with('success', 'Dealer updated successfully.');
    }

    public function destroy(Admin $dealer)
    {
        $dealer->delete();
        return redirect()->back();
    }

    public function show($id)
    {

        $dealer = Admin::find($id);
        return view('admin.oils-dealer.show', compact('dealer'));
    }

}

resources/views/admin/oils-dealer/create.blade.php
@extends('admin.layouts.layout')

@section('heading')
    <h4>
        <a href="{{ route('admin.pages.home') }}">
            <i class="icon-arrow-left52 mr-2"></i>
        </a>
        <span class="font-weight-semibold">Home - Oil Dealers</span>
    </h4>
@endsection

@section('breadcrumbs')
    <div class="breadcrumb">
        <a href="{{ route('oils-dealers.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item">Oil Dealer</span>
        <span class="breadcrumb-item active">Create</span>
    </div>
@endsection

@section('content')
    @include('admin.partials.header')
    <div class="content">
        @include('common.partials.flash')

        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Oil Dealer</h5>
            </div>

            <div class="card-body">
                <form action="{{ route('oils-dealers.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold @error('name') text-danger @enderror">User Name <span
                                    class="text-red">*</span></label>
                            <div class="form-group-feedback form-group-feedback-right">
                                <input type="text" name="name" value="{{ old('name') }}"
                                    class="form-control @error('name') border-danger @enderror" required>
                                @error('name')
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-cancel-circle2"></i>
                                </div>
                                @enderror
                            </div>
                            @error('name')
                            <span class="form-text text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold @error('business_name') text-danger @enderror">Business Name </label>
                            <div class="form-group-feedback form-group-feedback-right">
                                <input type="text" name="business_name" value="{{ old('business_name') }}"
                                    class="form-control @error('business_name') border-danger @enderror" >
                                @error('business_name')
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-cancel-circle2"></i>
                                </div>
                                @enderror
                            </div>
                            @error('business_name')
                            <span class="form-text text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label class="font-weight-semibold @error('contact') text-danger @enderror">Contact <span
                                    class="text-red">*</span></label>
                            <div class="form-group-feedback form-group-feedback-right">
                                <input type="text" name="contact" value="{{ old('contact') }}"
                                    class="form-control @error('contact') border-danger @enderror" required>
                                @error('contact')
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-cancel-circle2"></i>
                                </div>
                                @enderror
                            </div>
                            @error('contact')
                            <span class="form-text text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label class="font-weight-semibold @error('nic') text-danger @enderror">NIC
                            <span class="text-red">*</span> </label>
                            <div class="form-group-feedback form-group-feedback-right">
                                <input type="text" name="nic" value="{{ old('nic') }}"
                                    class="form-control @error('nic') border-danger @enderror" >
                                @error('nic')
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-cancel-circle2"></i>
                                </div>
                                @enderror
                            </div>
                            @error('nic')
                            <span class="form-text text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label class="font-weight-semibold @error('email') text-danger @enderror">Email
                            <span class="text-red">*</span> </label>
                            <div class="form-group-feedback form-group-feedback-right">
                                <input type="text" name="email" value="{{ old('email') }}"
                                    class="form-control @error('email') border-danger @enderror" >
                                @error('email')
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-cancel-circle2"></i>
                                </div>
                                @enderror
                            </div>
                            @error('email')
                            <span class="form-text text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold @error('address') text-danger @enderror">Address <span
                                    class="text-red">*</span></label>
                            <div class="form-group-feedback form-group-feedback-right">
                                <input type="text" name="address" value="{{ old('address') }}"
                                    class="form-control @error('address') border-danger @enderror" required>
                                @error('address')
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-cancel-circle2"></i>
                                </div>
                                @enderror
                            </div>
                            @error('address')
                            <span class="form-text text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold @error('city') text-danger @enderror">City
                            <span class="text-red">*</span> </label>
                            <div class="form-group-feedback form-group-feedback-right">
                                <input type="text" name="city" value="{{ old('city') }}"
                                    class="form-control @error('city') border-danger @enderror" >
                                @error('city')
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-cancel-circle2"></i>
                                </div>
                                @enderror
                            </div>
                            @error('city')
                            <span class="form-text text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold @error('image') text-danger @enderror">Picture
                         </label>
                        <div class="form-group-feedback form-group-feedback-right">
                            <input type="file" accept=".jpeg,.png,.bmp,.gif,.svg,.webp,.jpg" name="image" >
                            <span class="form-text text-muted">Accepted formats: jpeg, png, bmp, gif, svg, jpg, or webp</span>
                            @error('image')
                            <div class="form-control-feedback text-danger">
                                <i class="feature_image-cancel-circle2"></i>
                            </div>
                            @enderror
                        </div>
                        @error('image')
                        <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="text-right">
                        <span class="text-muted" style="margin-right:3%">Default Password is 12345678 </span>
                        <button type="submit" class="btn btn-primary">Submit <i class="icon-paperplane ml-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/oils-dealer/index.blade.php
@extends('admin.layouts.layout')

@section('heading')
    <h4><a href="{{ route('oils-dealers.index') }}"><i class="icon-arrow-left52 mr-2"></i></a> <span
            class="font-weight-semibold">Home - Oil Dealers</span> - View All</h4>
@endsection

@section('breadcrumbs')
    <div class="breadcrumb">
        <a href="{{ route('oils-dealers.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item">Oil Dealers</span>
        <span class="breadcrumb-item active">View All</span>
    </div>
@endsection

@section('content')
   @include('admin.partials.header')
    <div class="content">
        @include('common.partials.flash')
        <div class="card has-table">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">All Dealers</h5>
                <div class="header-elements">
                    <a href="{{ route('oils-dealers.create') }}" class="mt-2 btn btn-primary">
                        Add New Dealer
                    </a>
                </div>
            </div>
            <table class="table datatable-basic">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Business Name</th>
                    <th>Contact</th>
                    <th>Address</th>
                    <th>Registered at</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                @forelse ($dealers as $dealer)
                    <tr> <td>
                        @if($dealer->picture)
                        <img src="{{ (config('app.url'). '/mechon/storage/app/public/'. $dealer->picture) }}" height="120px" width="120px"/>
                        @else
                        <p> No image uploaded </p>
                        @endif
                        </td>
                        <td>{{ $dealer->name }}</td>

                        <td>{{ $dealer->business_name }}</td>
                        <td>{{ $dealer->contact }}</td>
                        <td>{{ $dealer->address }}</td>
                        <td>{{ $dealer->created_at }} </td>
                        <td class="text-center">
                            <div class="list-icons">
                                <div class="dropdown">
                                    <a href="#" class="list-icons-item" data-toggle="dropdown">
                                        <i class="icon-menu9"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a href="{{ route('oils-dealers.edit', $dealer->id) }}"
                                           class="dropdown-item"><i class="icon-pencil5"></i> Edit
                                        </a>
                                        <a href="{{ route('oils-dealers.show', [$dealer->id]) }}" class="dropdown-item">
                                            <i class="icon-eye"></i>
                                            Show
                                        </a>
                                        <a href="#" class="dropdown-item"
                                           onclick="event.preventDefault(); if(confirm('Are you sure you want to perform this action?')){document.getElementById('delete-post-{{ $dealer->id }}-form').submit();}">
                                            <i class="icon-trash"></i>
                                            Delete
                                        </a>
                                        <form action="{{ route('oils-dealers.destroy', $dealer->id) }}"
                                              id="delete-post-{{ $dealer->id }}-form" method="POST"
                                              style="display: none;">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7">
                            <div class="alert alert-info text-center">
                                No Dealer Added So Far
                                <br>
                                <a href="{{ route('oils-dealers.create') }}" class="mt-2 btn btn-primary">
                                    Create New Dealers
                                </a>
                            </div>
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            {!! $dealers->links() !!}
        </div>
    </div>
@endsection