routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/cache', function () {
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    return "<h1>Cache Clear</h1>";
});

Route::get('/home-repairing-services', 'HomeServiceController@index')->name('home-services.index')->middleware('auth');
Route::post('/home-services/home-repairing-services', 'HomeServiceController@HomeRepairingServices')->middleware('auth');
Route::post('/home-services/validate-step-one', 'HomeServiceController@validateStepOne')->middleware('auth');
Route::post('/home-services/validate-step-two', 'HomeServiceController@validateStepTwo')->middleware('auth');
Route::post('/home-services/validate-step-three', 'HomeServiceController@validateStepThree')->middleware('auth');
Route::post('/home-services/validate-step-four', 'HomeServiceController@validateStepFour')->middleware('auth');
Route::post('/home-services/validate-step-five', 'HomeServiceController@validateStepFive')->middleware('auth');
Route::get('sendSMS', 'TwilioSMSController@index')->name('sms');

Route::get('/oils', 'EngineOilController@index')->name('engine-oil.index');
Route::post('/add-to-cart/oil/{id}', 'EngineOilController@addOil')->middleware('auth');
Route::get('/get-cart/', 'CartController@getCart');

// Route::post('/engine-oil/engine-oil-purchase', 'EngineOilController@engineOilPurchase')->middleware('auth');
// Route::post('/engine-oil/validate-step-one', 'EngineOilController@validateStepOne')->middleware('auth');

Route::post('/workshop/reviews', 'PageController@reviewsSubmit')->middleware('auth');
Route::post('/workshop/reviews/{workshop}', 'PageController@reviewsShow');

Route::post('/add-to-cart/spare-part/{id}', 'CartController@addSparePart')->middleware('auth');
Route::post('/change-up-cart/price/{cart}', 'CartController@changeUpCartPrice')->middleware('auth');
Route::post('/change-down-cart/price/{cart}', 'CartController@changeDownCartPrice')->middleware('auth');
Route::post('/remove/cart/{cart}', 'CartController@removeCart')->middleware('auth');
Route::get('/cart', 'CartController@index')->name('pages.cart')->middleware('auth');
Route::get('/cart/checkout', 'CartController@cartCheckout')->name('pages.cart-checkout')->middleware('auth');
Route::post('/cart/checkout/place-order', 'CartController@placeOrder')->name('pages.place-order')->middleware('auth');

Route::get('/', 'PageController@index')->name('pages.home');
Route::get('/about', 'PageController@about')->name('pages.about');
Route::get('/customer-complaints', 'PageController@customerComplaints')->name('pages.customer-complaints');
Route::post('/customer-complaints/submit', 'PageController@complaintsSubmit')->name('pages.complaints.submit');
Route::get('/emergency-towing-repairing', 'PageController@emergencyTowing')->name('pages.emergency-towing')->middleware('auth');
Route::post('/emergency-towing-repairing/request', 'PageController@emergencyTowingRequest')->name('pages.emergency-towing.request')->middleware('auth');

Route::get('/workshops', 'PageController@workshops')->name('pages.frontend.workshops');
Route::get('/workshop/{slug}/details', 'PageController@workshopDetails')->name('pages.frontend.workshop-details');
Route::post('/search/workshops', 'PageController@searchWorkshops')->name('pages.search.workshops');
Route::get('/spare-parts', 'PageController@spareParts')->name('pages.frontend.spare-parts');
Route::get('/spare-parts/{slug}/details', 'PageController@sparePartDetails')->name('pages.frontend.spare-part-details');
//Route::get('/oils', 'PageController@oils')->name('pages.frontend.oils');
Route::get('/oils/{slug}/details', 'PageController@oilDetails')->name('pages.frontend.oil-details');
Route::get('/services', 'PageController@services')->name('pages.frontend.services');
Route::get('/service/{slug}/details', 'PageController@serviceDetails')->name('pages.frontend.service-details');

Route::post('/search/spare-parts', 'PageController@searchSpareParts')->name('pages.search.spare-parts');
Route::get('/contact-us', 'PageController@contactUs')->name('pages.contact-us');
Route::get('/service-repairs-maintenance', 'PageController@serviceRepairsMaintenance')->name('pages.maintenance');
Route::post('/vehicle-information', 'PageController@vehicleInformation');
Route::post('/validate-step-one', 'PageController@validateStepOne');
Route::post('/validate-step-two', 'PageController@validateStepTwo');
Route::post('/validate-step-three', 'PageController@validateStepThree');
Route::post('/validate-step-four', 'PageController@validateStepFour');
Route::post('/validate-step-five', 'PageController@validateStepFive');
Route::Post('/get-all/models/{id}', 'PageController@getAll');
Route::Post('/get-all/spare-parts/{id}', 'PageController@getAllParts');
Route::Post('/get-all/workshop/spare-parts', 'PageController@getAllWorkshopParts');
Route::Post('/get/workshop/{workshop}/car/{car}/model/{id}', 'PageController@getWorkshopCarModel');
Route::Post('/get-all/workshop/model/spare-parts/{id}', 'PageController@getAllModelParts');
Route::Post('/get-all/workshop/model/spare-parts', 'PageController@getAllWorkshopParts');
Route::Post('/get-all/price/spare-parts', 'PageController@getAllPriceParts');
Route::Post('/get-all/workshop/models/{model}/cars/{car}/spare-parts', 'PageController@getAllWorkshopModelCarParts');

Route::Post('/get-all/workshop/{city}', 'PageController@getAllWorkshopCities');
Route::Post('/get-all/workshop', 'PageController@getAllWorkshop');
Route::Post('/get-all/services/{workshop}', 'PageController@getAllServices');
Route::Post('/get-all/car/models/{id}', 'PageController@getAllCarModels');

Auth::routes();
Route::post('workshop/register', 'Auth\RegisterController@workshopRegister')->name('workshop.register');

Route::group(['prefix' => 'admin', "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/', function () {
        return redirect(route("admin.login"));
    });
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['prefix' => 'admin', "middleware" => "auth:admin", "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/change-password', 'ChangePasswordController@changePassword')->name('change-password.edit');
    Route::put('/change-password', 'ChangePasswordController@updatePassword')->name('change-password.update');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin', "namespace" => "Admin"], function () {
    Route::get('/', 'PageController@index')->name('admin.pages.home');
    Route::post('/filter', 'PageController@filter')->name('admin.home.filter');

    Route::get('/complaints', 'PageController@complaints')->name('complaints');
    Route::get('/emergencies-towing', 'EmergencyController@index')->name('emergencies-towing.index');

    Route::resource('workshops', 'WorkshopController');
    Route::get('/workshop/change-password', 'WorkshopController@changePassword')->name('admin.workshops.change-password');
    Route::put('/workshop/update-password', 'WorkshopController@updatePassword')->name('admin.workshops.update-password');
    Route::get('/workshop/{id}/set-status/{status}', 'WorkshopController@setStatus')->name('admin.workshop-status');

    Route::resource('reviews', 'ReviewController');
    Route::resource('oils', 'OilController');
    Route::get('/oil/image-delete/{oil}/{image}', 'OilController@delete')->name('oil.picture.delete');

    Route::get('/service/image-delete/{service}/{image}', 'ServiceController@delete')->name('service.picture.delete');

    Route::resource('services', 'ServiceController');
    Route::resource('bookings', 'BookingController');
    Route::resource('orders', 'OrderController');
    Route::resource('cars', 'CarController');
    Route::resource('models', 'ModelController');
    Route::resource('oils-dealers', 'OilsDealerController');
    Route::resource('parts-dealers', 'PartsDealerController');
    Route::resource('labours', 'LabourController');

    Route::post('/order/status', "OrderController@status")->name("order.status");
    Route::post('/booking/status', "BookingController@status")->name("booking.status");

    Route::resource('parts', 'SparePartsController');
    Route::get('/part/image-delete/{part}/{image}', 'SparePartsController@delete')->name('part.picture.delete');

    Route::resource('users', 'UserController');
    Route::get('/{id}/set-status/{status}', 'UserController@setStatus')->name('admin.user-status');
    Route::get('/user/{user}/change-password', 'UserController@changePassword')->name('admin.users.change-password');
    Route::put('/user/{user}/update-password', 'UserController@updatePassword')->name('admin.users.update-password');
    // Contact Inquiries
    Route::get('/general-settings/create', "GeneralSettingController@create")->name("general-settings.create");
    Route::post('/general-settings', "GeneralSettingController@store")->name("general-settings.store");

app/Oil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Oil extends Model
{
    protected $guarded = [];
    protected $table = 'oils';

    public function carts()
    {
        return $this->hasMany(Cart::class);
    }

    public function checkouts()
    {
        return $this->hasMany(CheckoutDetails::class);
    }

    public function pictures()
    {
        return $this->hasMany(OilsPictures::class);
    }

    public function cars()
    {
        return $this->belongsToMany(Car::class, 'car_oils');
    }
}

app/Http/Controllers/Admin/OilController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Admin;
use App\Http\Controllers\Controller;
use App\Oil;
use App\OilsPictures;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class OilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $oils = Oil::latest()->paginate(10);
        return view('admin.oils.index', compact('oils'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $dealers = Admin::role('oil_dealer')->paginate(10);

        return view('admin.oils.create', compact('dealers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255', 'unique:oils'],
            'wholesale_price' => ['required', 'integer'],
            'retail_price' => ['required', 'integer'],
            'oil_rate' => ['required', 'integer'],
            'bulk_orders_retail_price' => ['required', 'integer'],
            'image' => ['required', 'array'],
        ]);

        $slug = Str::slug($data['name'], '-');
        $oil = new Oil;
        $oil->name = $request->name;
        $oil->slug = $slug;
        $oil->brand = $request->brand_name;
        $oil->category = $request->category;
        $oil->wholesale_price = $request->wholesale_price;
        $oil->retail_price = $request->retail_price;
        $oil->oil_rate = $request->oil_rate;
        $oil->bulk_orders_retail_price = $request->bulk_orders_retail_price;
        $oil->discount = $request->discount;
        $oil->quantity = $request->quantity;
        $oil->description = $request->description;
        $oil->suggestions = $request->suggestion;
        $oil->company = '';
        //$oil->user_id = Auth::user()->id;
        $oil->user_id = $request->added_by;
        $oil->added_by = "oil_dealer";
        $oil->save();

        $id = $oil->id;
        $images = $request->image;

        foreach ($images as $image) {
            $filename = Str::random(15) . '.' . $image->extension();
            Storage::putFileAs("public", $image, $filename);

            OilsPictures::create(['oil_id' => $id, 'path' => $filename]);

        }
        return redirect()->route('oils.index')->with('success', 'Oil created successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Oil $oil)
    {
        $pictures = OilsPictures::where('oil_id', $oil->id)->get();
        $dealers = Admin::role('oil_dealer')->paginate(10);
        return view('admin.oils.edit', compact('oil', 'pictures', 'dealers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Oil $oil)
    {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'wholesale_price' => ['required', 'integer'],
            'retail_price' => ['required', 'integer'],
            'oil_rate' => ['required', 'integer'],
            'bulk_orders_retail_price' => ['required', 'integer'],
        ]);

        $slug = Str::slug($data['name'], '-');
        $oil = Oil::find($oil->id);
        $oil->name = $request->name;
        $oil->slug = $slug;
        $oil->brand = $request->brand_name;
        $oil->category = $request->category;
        $oil->wholesale_price = $request->wholesale_price;
        $oil->retail_price = $request->retail_price;
        $oil->oil_rate = $request->oil_rate;
        $oil->bulk_orders_retail_price = $request->bulk_orders_retail_price;
        $oil->discount = $request->discount;
        $oil->quantity = $request->quantity;
        $oil->description = $request->description;
        $oil->suggestions = $request->suggestion;
        $oil->user_id = $request->added_by;
        $oil->company = '';
        $oil->save();

        $id = $oil->id;
        $images = $request->image;

        if ($images) {
            foreach ($images as $image) {
                $filename = Str::random(15) . '.' . $image->extension();
                Storage::putFileAs("public", $image, $filename);
                OilsPictures::create(['oil_id' => $id, 'path' => $filename]);
            }
        }

        return redirect()->route('oils.index')->with('success', 'Oil updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Oil $oil)
    {
        OilsPictures::where(['oil_id' => $oil->id])->delete();
        $oil->delete();
        return redirect()->back();
    }

    public function delete(Request $request, $id, $image)
    {
        Storage::delete('public/' . $image);
        OilsPictures::where(['oil_id' => $id, 'path' => $image])->delete();

        $request->session()->flash('message', 'Delete Image successfully');
        $request->session()->flash('alert-class', 'alert alert-success');
        return redirect()->back();
    }

    public function show(Oil $oil)
    {
        $pictures = OilsPictures::where('oil_id', $oil->id)->get();

        return view('admin.oils.show', compact('oil', 'pictures'));
    }
}

resources/views/admin/oils/index.blade.php
@extends('admin.layouts.layout')

@section('heading')
    <h4><a href="{{ route('oils.index') }}"><i class="icon-arrow-left52 mr-2"></i></a> <span
            class="font-weight-semibold">Home - Oils</span> - View All</h4>
@endsection

@section('breadcrumbs')
    <div class="breadcrumb">
        <a href="{{ route('oils.index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item">Oils</span>
        <span class="breadcrumb-item active">View All</span>
    </div>
@endsection

@section('content')
   @include('admin.partials.header')
    <div class="content">
        @include('common.partials.flash')
        <div class="card has-table">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">All Oils</h5>
                <div class="header-elements">
                    <a href="{{ route('oils.create') }}" class="mt-2 btn btn-primary">
                        Create New Oil
                    </a>
                </div>
            </div>
            <table class="table datatable-basic">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Brand</th>
                    <th>Retail Price</th>
                    <th>Dealer</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                @forelse ($oils as $oil)
                    <tr> <td>
                        @php

                        if ($pic = $oil->pictures->first()) {

                        @endphp
                            <img src="{{ (config('app.url'). '/mechon/storage/app/public/'. $pic->path) }}" height="120px" width="120px"/>
                        @php
                    }
                        @endphp
                        </td>
                        <td>{{ $oil->name }}</td>

                        <td>{{ $oil->brand }}</td>
                        <td>{{ $oil->retail_price }}</td>
                        @php

                        $admin = \App\Admin::where('id', $oil->user_id)->first();
                            @endphp
                        <td>{{  $admin->business_name}} </td>
                        <td class="text-center">
                            <div class="list-icons">
                                <div class="dropdown">
                                    <a href="#" class="list-icons-item" data-toggle="dropdown">
                                        <i class="icon-menu9"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a href="{{ route('oils.edit', $oil->id) }}"
                                           class="dropdown-item"><i class="icon-pencil5"></i> Edit
                                        </a>
                                        <a href="{{ route('oils.show', [$oil->id]) }}" class="dropdown-item">
                                            <i class="icon-eye"></i>
                                            Show
                                        </a>
                                        <a href="#" class="dropdown-item"
                                           onclick="event.preventDefault(); if(confirm('Are you sure you want to perform this action?')){document.getElementById('delete-post-{{ $oil->id }}-form').submit();}">
                                            <i class="icon-trash"></i>
                                            Delete
                                        </a>
                                        <form action="{{ route('oils.destroy', $oil->id) }}"
                                              id="delete-post-{{ $oil->id }}-form" method="POST"
                                              style="display: none;">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7">
                            <div class="alert alert-info text-center">
                                No Oils Added So Far
                                <br>
                                <a href="{{ route('oils.create') }}" class="mt-2 btn btn-primary">
                                    Create New Oil
                                </a>
                            </div>
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            {!! $oils->links() !!}
        </div>
    </div>
@endsection

resources/views/admin/oils/show.blade.php
@extends('admin.layouts.layout')

@section('heading')
    <h4>
        <a href="{{ route('admin.pages.home') }}">
            <i class="icon-arrow-left52 mr-2"></i>
        </a>
        <span class="font-weight-semibold">Home - Oils</span> - Show
    </h4>
@endsection

@section('breadcrumbs')
<div class="breadcrumb">
    <a href="{{ route('admin.pages.home') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
    <span class="breadcrumb-item"><a href="{{ route('oils.index') }}"> Oils </a></span>
</div>
@endsection

@section('content')
@include('admin.partials.header')
    <div class="content">
        @include('common.partials.flash')
        <div class="card has-table">
                <fieldset class="mb-3 mt-3 ml-2">
                    <legend class="text-uppercase font-size-sm font-weight-bold mb-0" style="font-size:18px;">Oil Details</legend>
                </fieldset>

            <div class="row" style="padding:2%">

                <div class="col-md-3">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Oil Name</h6>
                        </div>

                        <div class="card-body">
                            {{ $oil->name }}
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Brand Name</h6>
                        </div>

                        <div class="card-body">
                            {{ $oil->brand }}
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Category</h6>
                        </div>

                        <div class="card-body">
                            {{ $oil->category }}
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Oil Price</h6>
                        </div>

                        <div class="card-body">
                            {{ $oil->oil_rate }}
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Retail Price</h6>
                        </div>

                        <div class="card-body">
                            {{ $oil->retail_price }}
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Wholesale Price</h6>
                        </div>

                        <div class="card-body">
                            {{ $oil->wholesale_price }}
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Bulk Order Retail Price</h6>
                        </div>

                        <div class="card-body">
                            {{ $oil->bulk_orders_retail_price }}
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Discount</h6>
                        </div>

                        <div class="card-body">
                            {{ $oil->discount }}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Description</h6>
                        </div>
                        <div class="card-body">
                            {!! $oil->description !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Suggestion</h6>
                        </div>

                        <div class="card-body">
                            {!! $oil->suggestions !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Quantity</h6>
                        </div>

                        <div class="card-body">
                            {{ $oil->quantity }}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card border-teal-400">
                        <div class="card-header bg-teal-400 text-white header-elements-inline">
                            <h6 class="card-title">Dealer</h6>
                        </div>
                        @php
                            $admin = \App\Admin::where('id', $oil->user_id)->first();
                        @endphp
                        <div class="card-body">
                            {{ $admin->business_name }}
                        </div>
                    </div>
                </div>


                <div class="col-md-12">
                        <label style="display: block;"
                            class="font-weight-semibold @error('image') text-danger @enderror">Images </label>
                        <div class="d-inline-block" style="position: relative;margin-bottom: inherit;">
                        @if($pictures)
                            @foreach($pictures as $image)

                                <div class="d-inline-block" style="position:relative;margin-bottom: inherit; ">
                                    <img src="{{ (config('app.url'). '/mechon/storage/app/public/'. $image->path) }}" height="200px" width="200px"/>

                                </div>
                            @endforeach
                        @else
                            <p>No Image Found</p>
                        @endif

                        </div>
                </div>

            </div>

        </div>
    </div>
@endsection